# Generated by Django 3.0.3 on 2020-07-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_to_exam', models.CharField(choices=[('PCR', 'RT-PCR'), ('SO', 'Sorologia'), ('TRAG', 'Teste Rápido - Antígenos'), ('TRAC', 'Teste Rápido - Anticorpos')], default='PCR', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('born_date', models.DateField()),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TestType')),
            ],
        ),
    ]
